# Be sure to restart your server when you modify this file.

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "development_secret_key_base_#{SecureRandom.hex(64)}" %>

test:
  secret_key_base: test_secret_key_base

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || raise("SECRET_KEY_BASE environment variable is not set") %>
